---
- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: Creates directory
  file:
    path: ~/backend
    state: directory

- name: Copy backend dist files web server
  copy:
    src: artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: Uncompress Backend
  shell: |
    cd ~/backend
    tar xvzf artifact.tar.gz -C .
    ls -la
    
- name: Build
  become: true
  shell: |
    cd ~/backend
    npm install
    npm run build
    
- name: Start PM2
  shell: |
    cd ~/backend 
    pm2 start npm --name backend -- start